// <auto-generated />
namespace BitsolMeritInSchoolSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class creatingexistingtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creatingexistingtables));
        
        string IMigrationMetadata.Id
        {
            get { return "201903021645265_creating existing tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
